on: [push]

jobs:
  job_1:
    name: Upload Function to Segment
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout Function
        uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "Function Text is"
          cp lib/function.js lib/function.txt
          value=`cat lib/function.txt`
          echo $value
          echo "::set-output name=function_code::$value"
        id: checkout
      - name: Sending Function to Segment
        uses: ./ # Uses an action in the root directory
        with:
          token: 'Mona the Octocat'
          function-js: ${{ steps.checkout.outputs.function_code }}
