on: [push]

jobs:
  job_1:
    name: Upload Function to Segment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Preparing Function
        uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "Function Code Is"
          cp lib/function.js lib/function.txt
          value=`cat lib/function.txt`
          echo $value
          echo "::set-output name=function_code::$value"
        id: checkout
      - name: Sending Function to Segment
        uses: ./ # Uses an action in the root directory
        with:
          token: 'Mona the Octocat'
          function-code: ${{ steps.checkout.outputs.function_code }}
          function-name: 'Sam New Test Function'
          workspaceID: VtDtj9zzck
          function-id: dfn_5eb99f2c2d633a328e850f4b
